### ISSUE TITLE
Tokenization of metadata

### ISSUE THREAD

**Issue by kbrabrand** [imbo/imbo-metadata-search#9]
By default strings are tokenized in elasticsearch, so right now a search for

```js
{ "animal":"red panda" }
```

would result in hits for all the following; `red fox`, `red panda` and `giant panda`.

What do you think is the best way to ensure this works in a predictable way? Is just telling people to configure their indices correctly enough?

**Comment by fangel** [comment]
I think this partially depends on the order of the returned images.

In my mind, it makes sense that a search for "red panda" then return the result-set "red panda, giant panda, red fox" because it's listed in order of how well they match the input query.

The problem is if you have an explicit sort on something that's not the search-score, then the results can seem to not match very well. But we have been using something with this behaviour to search for articles for 6 months and have gotten no bad responses from the journalists.

**Comment by kbrabrand** [comment]
I agree. I guess that leaving this as is and addressing the sorting stuff would be enough.

But this implicitly means that in some cases we have no way of matching "red panda", and nothing else. Do we need a way of querying for an exact match?

**Comment by fangel** [comment]
I don't know if we need one, but it would be quite easy to add if we feel a need for it.

But does exact matches mean that "red panda" shouldn't match "red panda eats bamboo", or just that all of the words must be present in the result. Or that they must appear as is, that is "red panda eats bamboo" matches, but "panda likes the color red" shouldn't. There are many different ways to define what it means to match...

**Comment by kbrabrand** [comment]
I guess what I would want here is a way of doing something similar to a string wrapped in double quotes when Googling, but I guess we can wait with this until the need is actually there. As you mention, you've been using this for several months without complaints.
